@baseUrl = http://127.0.0.1:8000/

### Get all users
GET {{baseUrl}}/users
Accept: application/json

### Create a new user
POST {{baseUrl}}api/accounts/register/
Content-Type: application/json

{
  "full_name": "  Fillibister    ",
  "email": "hbt@gmail.com",
  "password": "     tell me more    "
}

### Login user
POST {{baseUrl}}api/accounts/login/
Content-Type: application/json

{
  "email": "hbt@gmail.com",
  "password": "tell me more"
}

### Get Refresh Token
POST {{baseUrl}}api/accounts/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Njg3MTk2NiwiaWF0IjoxNzU2Nzg1NTY2LCJqdGkiOiIxOWQ4NWRiNTc0MWM0MGExODhmYWM1MWMwNTg0YTUzYiIsInVzZXJfaWQiOiIxIn0.k4Aw7YNZyyq7eKp-dvlON4vE7WRWGmcxUKtWD08mCa8"
}

### Reset Password
POST {{baseUrl}}api/accounts/reset-password/
Content-Type: application/json

{
  "token": "IYpKICYx_bNuO37pgzX54DKg9VGKex7g5YXIpFAC",
  "new_password": "password_here"
}

### Forgot Password
POST {{baseUrl}}api/accounts/forgot-password/
Content-Type: application/json

{
  "email": "h@gmail.com"
}