
services:
  web:
    build: .
    container_name: authservice_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: authservice_db
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: authservice_redis
    restart: always
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL}
    ports:
      - "6379:6379"

volumes:
  postgres_data: